### PR TITLE
Fix pedantic CocoaPods warning about using quotes vs angles

### PR DESCRIPTION
**Pull request by adamkaplan**
This prevents any other library from using this library as a dependency with CP 0.38

```
➜  SDCAlertView git:(master) ✗ pod spec lint

 -> SDCAlertView (2.5.2)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS]  SDCAlertView/SDCAlertView/Source/SDCDemoViewController.m:13:9: error: 'UIView+SDCAutoLayout.h' file not found with <angled> include; use "quotes" instead

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors.
```

### CODE REVIEW

**Comment by adamkaplan** [comment]
Mistake--

**Comment by sberrevoets** [comment]
I tried this myself and it looks like you're right - I get the same error. A fix for that is coming within the hour.

**Comment by adamkaplan** [comment]
@sberrevoets fwiw, I can't seem to compile the project successfully. Not sure why...

**Comment by adamkaplan** [comment]
Ah- looks like this Pods checker script is no longer valid.
```
diff "${PODS_ROOT}/../Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
if [[ $? != 0 ]] ; then
    cat << EOM
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
EOM
    exit 1
fi
```

**Comment by sberrevoets** [comment]
Just pushed some fixes. Running `pod spec lint` locally returns some warnings (that I'm not getting in Xcode itself), but you should be able to build now.

I'm also working on version 3.0 written in Swift that should mitigate these problems.

**Comment by adamkaplan** [comment]
@sberrevoets It looks better. When can 2.5.3 be pushed so that I can release my downstream lib? ;-)

**Comment by sberrevoets** [comment]
I al-ways forget to do that :weary: Done now though.

**Comment by adamkaplan** [comment]
Great, thanks!
